### ISSUE TITLE
this script is not working.

### ISSUE THREAD

**Issue by secfb** [Sh1Yo/resolf#1]
```powershell
#/tmp/resolf|master ⇒  cat t.txt                                          
151.101.64.205
simple.com
http://simple.com
https://simple.com
#/tmp/resolf|master⚡ ⇒  ./resolf -d t.txt  
```
<img width="505" alt="1" src="https://user-images.githubusercontent.com/38748801/80510881-002f2700-8984-11ea-9e9d-6e4febb54f42.png">

**Comment by secfb** [comment]
the problem was with me.
<img width="710" alt="2" src="https://user-images.githubusercontent.com/38748801/80511865-5b154e00-8985-11ea-8fd5-5a27fd79091b.png">

**Comment by Sh1Yo** [comment]
Yes, there is no output to the terminal for now. I close it because you found the solution.
